// FOR ALL PRODUCTS
export const FETCH_ALL_PRODUCT_REQUEST = 'FETCH_ALL_PRODUCT_REQUEST';
export const FETCH_ALL_PRODUCT_SUCCESS = 'FETCH_ALL_PRODUCT_SUCCESS';
export const FETCH_ALL_PRODUCT_FAILURE = 'FETCH_ALL_PRODUCT_FAILURE';

// FOR SINGLE SINGLE_PRODUCT
export const FETCH_SINGLE_PRODUCT_REQUEST = 'FETCH_SINGLE_PRODUCT_REQUEST';
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS';
export const FETCH_SINGLE_PRODUCT_FAILURE = 'FETCH_SINGLE_PRODUCT_FAILURE';

// FOR CREATE PRODUCT
export const CREATE_SINGLE_PRODUCT_REQUEST = 'CREATE_SINGLE_PRODUCT_REQUEST';
export const CREATE_SINGLE_PRODUCT_SUCCESS = 'CREATE_SINGLE_PRODUCT_SUCCESS';
export const CREATE_SINGLE_PRODUCT_FAILURE = 'CREATE_SINGLE_PRODUCT_FAILURE';

// // FOR UPDATE
export const UPDATE_SINGLE_PRODUCT_REQUEST = 'UPDATE_SINGLE_PRODUCT_REQUEST';
export const UPDATE_SINGLE_PRODUCT_SUCCESS = 'UPDATE_SINGLE_PRODUCT_SUCCESS';
export const UPDATE_SINGLE_PRODUCT_FAILURE = 'UPDATE_SINGLE_PRODUCT_FAILURE';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
// FOR DELETE PRODUCT
export const DELETE_SINGLE_PRODUCT_REQUEST = 'DELETE_SINGLE_PRODUCT_REQUEST';
export const DELETE_SINGLE_PRODUCT_SUCCESS = 'DELETE_SINGLE_PRODUCT_SUCCESS';
export const DELETE_SINGLE_PRODUCT_FAILURE = 'DELETE_SINGLE_PRODUCT_FAILURE';
